version: '3.8'

services:
  backend:
    build:
      context: ./backend/pico-chat
      dockerfile: Dockerfile
    container_name: pico-chat-backend-container
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://db:5432/pico-chat
    platform: linux/amd64

  frontend:
    build:
      context: ./frontend/pico-chat
      dockerfile: Dockerfile
    container_name: pico-chat-frontend-container
    ports:
      - 3000:3000
    volumes:
      - ./frontend/pico-chat:/app
      - /app/node_modules
    command: sh -c "yarn dev"

  db:
    image: postgres:15
    container_name: pico-chat-db-container
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./backend/pico-chat/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pico-chat

volumes:
  db-store:
  node_modules:
