version: '3'

services:
  app:
    build: ./backend/pico-chat
    container_name: tmp-spring-boot
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pico-chat
      DB_USER: postgres
      DB_PASS: postgres
    platform: linux/amd64
  db:
    image: postgres:15
    container_name: pico-chat-container
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./backend/pico-chat/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pico-chat
volumes:
  db-store:
