spring:
    application:
        name: pico-chat

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:pico-chat}
        username: ${DB_USER:postgres}
        password: ${DB_PASS:postgres}

